### ISSUE TITLE
Setting up own cards

### ISSUE THREAD

**Issue by paulusm** [chuvidi2003/cardsorter#1]
Hi there, I've downloaded and set up the app as it looks like something I can use for a project.
It looks like I'd need to set up cards and codebook through SQL at this stage? Otherwise it is in a working state?

I've been looking for an O/S card sorting app for some time, so may be able to give you a hand!

**Comment by victordibia** [comment]
Hi Paul,

Thanks for your message. At the moment, you can set up cards through SQL or by running migrations with and seeding your database with some card data. To be honest, there is still a bit of testing to be done (and possible better db design decisions to be made). Current functionality.

# What Currently Work
- Once cards are setup
- Assign new user accounts to a project (permissions table)
- Users can login and view each project, and then assign cards to categories (card sorting) and each assignment is saved to the db (responses table) once the next button is pressed. 
  Responses are stored using  multiple db rows per card . Each row contains a card and the selection      status for each item/category.

# To be done/ Next Steps
- Preliminary Data Analysis and Download.  
  Generate a table of all responses for each use, show measures of inter rater reliability, allow for resolution of differing codes and also download of data as csv.
- Improve Data Loading for Cards
  Currently, I load all of the card data on page load within the main **task** section (which appears to make the app slow over the internet). I will be improving this to load only a subset of cards (possibly one or two cards) and load a new card from db when the next button is pressed.

Sorry that the project is a bit unorganized at the moment, I will be giving it more time in the coming weeks (can be a bit challenging juggling this and other work). 

Finally, thanks for the offer of collaboration, I am really happy to take any help I can get! Feel free to fork the project, add features and send a pull request! 

Kind regards,
Victor
victordibia.com
